### ISSUE TITLE
Various fixes

### ISSUE THREAD

**Issue by rigmar** [fidgetingbits/IDArling#51]
Hello!
I add some features and fix some issues in my fork.
 1) local_types_changed implemented. Now, not mapping to idb (not in "Structures" tab) types will be syncing.
2) All (i hoping) types and structures events use names instead ordinals or ID. With idb syncing mechanism (will be implemented later) it remove inconsistent idb problem.
3) UI hooks for handle MakeCode and Undefine by buttons "C" and "U"
4) Add buttons in Open\Save dialogs for delete group, project and database
5) Add setting "files_dir" to config and Settings dialog that specify where will the idb files be downloaded from the server.

So, it's fixes next issues:
Converting raw data to code not propagated? fidgetingbits#45
Type not synced with struct/enum tab not propagated in IDArling fidgetingbits#44
IDArling not supporting parsing a header file? fidgetingbits#42
IDArling not supporting new type IDs fidgetingbits#41

My commit  - https://github.com/rigmar/IDArling/commit/70eba9e0405c3fc303103d3da4cfa8cfeee6f587

**Comment by saidelike** [comment]
Thanks rigmar for this. I've created a Pull Request so am closing here as now it will be handled directly in https://github.com/fidgetingbits/IDArling/pull/52

**Comment by saidelike** [comment]
Thanks again for that @rigmar that is an amazing code update.

My few cents when merging:

- rename `UIHook` to `UIHooks`
- instead of commenting `pydevd_pycharm`, I've changed it to be enabled if `fDebug` is set (as was done by the original authors)
- I've refactored some code to avoid duplication (see `_handle_delete_group`, `_handle_delete_project` and `_handle_delete_database`)
- I've made spaces between arguments uniform (some didn't have a space)
- I think we need a lock for the delete database, group and project to avoid deleting an asset that someone else has currently opened? See https://github.com/fidgetingbits/IDArling/issues/53

One question:

* Why did you use `vu.refresh_view(False)` instead of `vu.refresh_view(True)` in `HexraysEvent.refresh_pseudocode_view(ea)`? It seems it won't update the hexrays window after updating the ctree, which could be bad if another user is modifying the same function? See https://www.hex-rays.com/products/decompiler/manual/sdk/structvdui__t.shtml#a44e1923f1e01bed28bf52f862520052d

Hopefully I did't break anything when merging but let me know please otherwise.

**Comment by rigmar** [comment]
Looks cool and workable! I will merge and test it soon. Thanks for reviewing/rewriting. Codestyle not my strong side.
About `vu.refresh_view(False)`, if `True` IDA perform regenerate microcode. Microcode generation base only on disassembled code and it is exclusive and expensive action. IDArling use `HexraysEvent.refresh_pseudocode_view(ea)` in situations that don't touching microcode layer. So, using microcode regeneration is redundant and lead to some problems and warnings when we have many `HexraysEvent.refresh_pseudocode_view(ea)` calling in a row. Regenerate microcode operation does not have time to complete between callings and IDA show error window. Also, it expensive and significantly increase redecompile time in large functions. If somewho changing pseudocode in the same function that you work it may realy annoy :smiley:. Ctree rebuild must be enough for work with `lvars` and their types. It was enough in my tests at least. If there are problems, it will be necessary to come up with something else.

**Comment by saidelike** [comment]
Thanks for the explanations. That makes sense.
